### ISSUE TITLE
[bug] Meshroom GUI crashes on feature extraction and then screen flickers when restarted

### ISSUE THREAD

**Issue by andreasdss** [alicevision/meshroom#1093]
Hello, 

I just downloaded Meshroom 2020 v.1.0. When I opened it I loaded a sample dataset to test the speed and new functions. I have run this dataset before in older versions. Shortly after it starts, the UI crashes while the console stays open. I closed the console and then tried to restart Meshroom, however all that happens is that the GUI opens but it doesn't load anything (no text or nodes) and instead the Rotating Gimbal handle appears large in the center of the screen and just flickers incessantly, the console opens but stays black. I can upload a screenrecord if necessary. On the screenshot the gimbal cant be seen because it flickers on an off. 
![image](https://user-images.githubusercontent.com/72764939/95786507-ff8f1080-0cd7-11eb-8767-00611d7db8e1.png)

**To Reproduce**
1. Go to the executable and run the program
2. The program opens but the GUI just flickers rapidly. 

**Expected behavior**
I expected the GUI to open up so I can start my project. 
**Screenshots**

**Log**
If applicable, copy paste the relevant log output (please embed the text in a markdown code tag "\`\`\`" )

**Desktop (please complete the following and other pertinent information):**
 - OS: Win10, i7 ,16GB RAM, Gefore 940MX
 - Python version [e.g. 2.6] (I dont know.)
 - Qt/PySide version [e.g. 5.12.4]
 - Meshroom version: Meshroom Release 2020 v.1

**Comment by fabiencastan** [comment]
Does https://github.com/alicevision/meshroom/releases/tag/v2020.1.1 solves your issue?

**Comment by natowi** [comment]
I can confirm similar GUI crashes not restricted to feature extraction. I´ll see if I am able to reproduce the issue.

**Comment by glbarak** [comment]
Same here - first time user.
Just downloaded version 2020.1.1. extracted zip and ran meshroom
Screen appears but just flickers. I can see the gimbal, several shades of "black", 3 sliders but other than that nothing can be done.
W10 Home, HP Pavilion, 16G RAM, GEOForce MX250

**Comment by DaedalDave** [comment]
Hi, I am having the same issue, new version of Meshroom downloaded 2020.1.1

Double click the meshroom icon, Command window starts the Meshroom UI, but the buttons text does not appear. (strange it worked once yesterday, but no change and its gone again). The 3D viewer dominates the screen. All text on buttons gone in the UI.

![image](https://user-images.githubusercontent.com/74570335/99313472-885d1700-2857-11eb-8fa5-232c0318028e.png)

Dell G3, i7 10750
Windows 10
Nvidia GeForce GTX1660Ti
16Gb RAM
Python - nothing installed ? - at least no report from Python --version in powershell, but the binaries are precompiled right?
PySide - sorry how to i check the version ?

Thanks in advance for help.

**Comment by bmarr** [comment]
I can confirm the same behavior as OP under the same initial conditions except that I am using Meshroom 2020 v.1.1

A _workaround_ may be to create a shortcut to Meshroom.exe and set it to start in _Windows 8 compatibility mode_. When I tried this the GUI appears stable with no flickering. In this compatibility mode, I did not exercise the application except to rotate the 3D view around a bit, so I don't know if it is compromised in any other way.

OS: Win10 20H2, i7-8750h ,16GB RAM, GeForce GTX1050 Ti
Python version [e.g. 2.6] (I don't know, this is a fresh re-install of Windows 10 that has not yet had Python installed.)
Qt/PySide version [e.g. 5.12.4] (I don't know, this is a fresh re-install of Windows 10 that has not yet had Qt installed.)
Meshroom version: Meshroom Release 2020 v.1.1

I have successfully used earlier versions of Meshroom on the this hardware.

**Comment by DaedalDave** [comment]
I have now tried installing the latest Python and QtPySide2 packages:

Python version 3.9.0
Pyside2 5.15.2

The issue remains that more often than not.  When I run the meshroom.exe the GUI screen appears, but the screen looses the button text and is dominated by the 3D viewer see screenshot (what you can't see from the screen grab is that the gimbal and grid are visible and controllable, but fill the screen behind all the GUI windows:
![image](https://user-images.githubusercontent.com/74570335/99917560-f0ed3d80-2d08-11eb-92bc-64e2f5c3629b.png)

This is however an intermittent problem, I have run the .exe twice successfully on different days, but do not know what was making the difference. As I say most of the time it is unusable. Could it be the graphics driver is using different chipsets on different days?...

...any advise welcome to help fix the bug. Thanks in advance.

**Comment by peter-ch** [comment]
I also experience the problem on Win10 x64 20H2 and solved it as suggested above by running in Windows 8 compatibility mode.

**Comment by DaedalDave** [comment]
Hi, thanks, yes this workaround works for me too.

**Comment by XxSushiCatxX** [comment]
> I can confirm the same behavior as OP under the same initial conditions except that I am using Meshroom 2020 v.1.1
> 
> A _workaround_ may be to create a shortcut to Meshroom.exe and set it to start in _Windows 8 compatibility mode_. When I tried this the GUI appears stable with no flickering. In this compatibility mode, I did not exercise the application except to rotate the 3D view around a bit, so I don't know if it is compromised in any other way.
> 
> OS: Win10 20H2, i7-8750h ,16GB RAM, GeForce GTX1050 Ti
> Python version [e.g. 2.6] (I don't know, this is a fresh re-install of Windows 10 that has not yet had Python installed.)
> Qt/PySide version [e.g. 5.12.4] (I don't know, this is a fresh re-install of Windows 10 that has not yet had Qt installed.)
> Meshroom version: Meshroom Release 2020 v.1.1
> 
> I have successfully used earlier versions of Meshroom on the this hardware.

This works for me thanks!

**Comment by natowi** [comment]
Is this issue resolved with the latest 2021.1.0 release?

**Comment by peter-ch** [comment]
I just tried it and it seems to be fixed.

**Comment by DaedalDave** [comment]
HI all,

Sorry I think this issue still persists.  I downloaded the 2021.0.1 release.  Sometimes its ok, sometimes the problem remains.
