### ISSUE TITLE
The process stopped after the completion of feature extraction

### ISSUE THREAD

**Issue by richard-bmc** [alicevision/meshroom#145]
I tried to run the photogrammetry process in console and GUI. However the process stops after the completion of feature extraction. What should I do to proceed further?

**Comment by gregoire-dl** [comment]
Hi, 
Can you please specify:
- the commit number of your local AliceVision
- the commit number of your local Meshroom

We recently merged a [bug fix](https://github.com/alicevision/AliceVision/commit/9afa9e7af93d2851f3ad1afa0547f4b2e553a708) in AliceVision which could solve your problem.
Could you try to update both repositories and let us now.

**Comment by richard-bmc** [comment]
The commit number of my local AliceVision: a304bddb2bf0e12da87eece006892260bed07664
The commit number of my local Meshroom: 0578adabe738d533d54a7c0ed7e755369b37efc1

**Comment by fabiencastan** [comment]
It probably stops because the FeatureExtraction node fails.
Can you provide the log of the FeatureExtraction step?

**Comment by richard-bmc** [comment]
Here's my log of feature extraction(I've remove some lines which are similar to each other):

Program called with the following parameters:
 * describerPreset = "normal"
 * describerTypes = "sift"
 * forceCpuExtraction = 1
 * input = "c:/users/richad/appdata/local/temp/MeshroomCache/CameraInit/5ca542f7a3740880536285cac48aeb2f37a0acf2/cameraInit.sfm"
 * maxThreads = 0 (default)
 * output = "c:/users/richad/appdata/local/temp/MeshroomCache/FeatureExtraction/3308ca0636bf28959917f00f6d4972a5cd742edf"
 * rangeSize = 16
 * rangeStart = 0
 * verboseLevel = "info"

[18:27:50.587950][info] Extracting sift features from view 'E:/Photogrammetry/WallSculpture/P_20180328_095150.jpg' [cpu]
[18:27:50.606951][info] Extracting sift features from view 'E:/Photogrammetry/WallSculpture/P_20180328_095225.jpg' [cpu]
// Similar logs are skipped
[18:27:51.150982][info] Extracting sift features from view 'E:/Photogrammetry/WallSculpture/P_20180328_095206.jpg' [cpu]
[18:28:00.555520][info]       10000 sift features extracted from view 'E:/Photogrammetry/WallSculpture/P_20180328_095031.jpg'
[18:28:01.013546][info]       10000 sift features extracted from view 'E:/Photogrammetry/WallSculpture/P_20180328_095036.jpg'
// Similar logs are skipped
[18:28:05.650812][info]       10000 sift features extracted from view 'E:/Photogrammetry/WallSculpture/P_20180328_095143.jpg'
[18:28:05.673813][info] Task done in (s): 18.752000

**Comment by fabiencastan** [comment]
Ok, so it seems to be running fine.
What is the status of the node at the end? Does it stop with an "ERROR" on the node (red in meshroom) or is it stuck in "RUNNING" (orange in meshroom)?
You can also check the status in the file: "c:/users/richad/appdata/local/temp/MeshroomCache/FeatureExtraction/3308ca0636bf28959917f00f6d4972a5cd742edf/0.status"

**Comment by richard-bmc** [comment]
1. The status color of the node was still orange while the pipeline was stocked.
2. Here's the content of the status file(I think it's OK):
```
{
    "status": "RUNNING", 
    "endDateTime": "", 
    "nodeType": "FeatureExtraction", 
    "nodeName": "FeatureExtraction_1", 
    "env": null, 
    "execMode": "LOCAL", 
    "graph": "", 
    "packageName": "aliceVision", 
    "hostname": "MoonShineExp40", 
    "elapsedTime": 0, 
    "startDateTime": "2018-07-16 12:04:39.174000", 
    "sessionUid": "b6a1c3c0-88ab-11e8-b1a4-0cc47a6d14f7", 
    "packageVersion": null, 
    "elapsedTimeStr": "0:00:00", 
    "commandLine": "aliceVision_featureExtraction  --describerTypes sift --forceCpuExtraction True --verboseLevel info --input \"c:/users/richad/appdata/local/temp/MeshroomCache/CameraInit/155c1215993d3234c5625e94dad9da8aa8b3edb0/cameraInit.sfm\" --describerPreset normal --output \"c:/users/richad/appdata/local/temp/MeshroomCache/FeatureExtraction/cb891ed3d7778e51e482c297705ee19a5ec93b7d\" --rangeStart 0 --rangeSize 23"
}
```
3. And here are some errors I copied from the console:
```
[2018-07-16 11:52:51,993][WARNING] == Error while loading the following plugins ==
  * simpleFarmSubmitter: No module named simpleFarm
```
```
Failed to download scene at QUrl("")
```
```
[2018-07-16 11:54:12,447][ERROR] Error while trying command 'Set Attribute 'Came
raInit_1.intrinsics'':
Traceback (most recent call last):
  File "C:\Projects\meshroom\meshroom\ui\commands.py", line 58, in tryAndPush
    res = command.redoImpl()
  ########## LOTS OF TRACINGS ARE OMITTED ##########
  File "C:\Projects\meshroom\meshroom\core\desc.py", line 144, in validateValue
    raise ValueError('FloatParam only supports float value (param:{}, value:{},
        type:{})'.format(self.name, value, type(value)))
ValueError: FloatParam only supports float value (param:p, value:, type:<type 'unicode'>)```

**Comment by fabiencastan** [comment]
The error: ```Error while trying command 'Set Attribute 'CameraInit_1.intrinsics'' ``` is surprising. I don't understand how you can get that.
@yann-lty Do you have an idea?

**Comment by yann-lty** [comment]
Yes it has been fixed in #156

**Comment by richard-bmc** [comment]
My problem remains. I have updated AliceVision(1134635) and Meshroom(4d213f9). Each time I start the process in Meshroom UI, it always stops at "feature extraction" stage. Then I restart the process again. It will proceed normally but always stops at "structure from motion" stage.
However, I do have a good output(sfm.abc, as the image uploaded), and the log of SfM shows the process has completed successfully. 
![fsm_abc](https://user-images.githubusercontent.com/6274803/43828090-1b3705d6-9b2e-11e8-8988-3a144bc87722.png)

**Comment by richard-bmc** [comment]
I found another weird thing. I copied the arguments for SfM and execute aliceVision_incrementalSfM.exe in console, it worked normally except it didn't terminate. Neither pressing "Ctrl + C" nor "Ctrl + Break" can stop it. I have to stop it from task manager.

**Comment by daprato** [comment]
Hi there, I just downloaded the recent version (2018.1.0)
I have the same problem, stuck on Extraction Feature:
![image](https://user-images.githubusercontent.com/21172936/44463359-78f1b380-a5e5-11e8-9e1a-43b342017b64.png)

Status: Running
and Log of this task says Task Done:
![image](https://user-images.githubusercontent.com/21172936/44463410-a0e11700-a5e5-11e8-9ba7-ec4c9e226e5e.png)

I tried with more pictures of course (like 60 shots around a stone), it broke-down the Extraction Freature in 2 task I'd say, and still stuck on the first one, even if the log says "task done".

Can't wait testing this opensource solution, any workaround ?

**Comment by daprato** [comment]
So i decided to Stop the process. And the status is now:

> {

    "status": "ERROR",
    "execMode": "LOCAL",
    "nodeName": "FeatureExtraction_1",
    "nodeType": "FeatureExtraction",
    "packageName": "aliceVision",
    "packageVersion": null,
    "graph": "",
    "commandLine": "aliceVision_featureExtraction  --input \"C:/Users/admin/AppData/Local/Temp/MeshroomCache/CameraInit/4228b637cf04dedade9dcf7261db457eaaf9fd5c/cameraInit.sfm\" --describerTypes sift --describerPreset normal --forceCpuExtraction True --verboseLevel info --output \"C:/Users/admin/AppData/Local/Temp/MeshroomCache/FeatureExtraction/37cb624ebba7399a2540295555f026edffe420d7\" --rangeStart 0 --rangeSize 5",
    "env": null,
    "startDateTime": "2018-08-22 07:50:11.404871",
    "endDateTime": "",
    "elapsedTime": 0,
    "hostname": "admin-PC",
    "sessionUid": "20cf1d28-a5fb-11e8-9132-94de802cb9b5",
    "returnCode": 15,
    "elapsedTimeStr": "0:00:00"
}<

Log still with:
[07:50:36.859233][info] Task done in (s): 25.085000

**Comment by eggnot** [comment]
![Uploading 2018-10-21 22-31-17.PNG…]()
the same. recent binaries on win7

**Comment by ChemicalXandco** [comment]
@sjscotti this issue has already been fixed so why use windows 7 as a base? Windows 7 is old and support will run out soon.

**Comment by sjscotti** [comment]
@ChemicalXandco ... The windows 10 version died in feature extraction but the windows 7 version got through it for my project.  So perhaps the W7 version is more robust than W10, or maybe there were other changes made to the W7 version that fixed my issue.
