### ISSUE TITLE
Meshroom 2025 doesent start

### ISSUE THREAD

**Issue by yllarvorno-lab** [alicevision/Meshroom#2846]
**Describe the problem**
Meshroom 2025 doesent start

**Screenshots**

<img width="520" height="307" alt="Image" src="https://github.com/user-attachments/assets/c0409869-6cce-4ab4-9708-f1301398d1ab" />

**Screenrecorder**

https://github.com/user-attachments/assets/124dbae4-91d8-4cb4-a243-2b05a213cb6a
****
**System**

Väljaanne	Windows 11 Pro for Workstations
Versioon	24H2
Installimisaeg	‎10.‎11.‎2024
Operatsioonisüsteemi järk	26100.4946
Kogemus	Windowsi funktsiooni kasutajaliidese pakett 1000.26100.197.0

**Comment by fabiencastan** [comment]
It seems that there are some false security issues if you install Meshroom in "C:\Program Files".
If you install it in another folder, it should be working fine.

**Comment by yllarvorno-lab** [comment]
Dear Fabien!

Thank you lot for support. Great result- the Meshroom 2025, congrats!

BR Üllar
________________________________

**Comment by mmccubbing** [comment]
I think there may be more going on here than just the security issue that initially popped up. I ran mine, and even after allowing the security prompt, the program still failed so long as it was run from any directory with a space in the name, not just "C:\Program Files\".

(Notice that the issue continues despite moving it out of "C:\Program Files\" to "C:\Meshroom Files\")

```
PS C:\Meshroom files\Meshroom> .\Meshroom.exe
PS C:\Meshroom files\Meshroom> Traceback (most recent call last):
  File "C:\Release\sources\Meshroom\venv\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 140, in run
  File "C:\Release\sources\Meshroom\setupInitScriptWindows.py", line 34, in run
  File "meshroom\ui\__main__.py", line 12, in <module>
  File "C:\Release\sources\Meshroom\meshroom\ui\app.py", line 292, in __init__
RuntimeError: Meshroom Command Line Error: 'PROJECT' argument should be a Meshroom project file (.mg).
Invalid value: 'files\Meshroom\Meshroom.exe'
```

The issue then resolves upon moving it to "C:\MeshroomFiles\"

```
PS C:\MeshroomFiles\Meshroom> .\Meshroom.exe
PS C:\MeshroomFiles\Meshroom> [2025-08-22 12:10:48.202507] [0x000087b0] [trace]   Embedded OCIO configuration file: 'C:\MeshroomFiles\Meshroom\aliceVision/share/aliceVision/config.ocio' found.
[QtAliceVisionImageIO] Plugin Initialized
[QtAliceVision] Plugin Initialized
…
```

It looks like OP has the same "Invalid value: 'files\Meshroom\Meshroom.exe'" line with the path cutoff at the space character, as my testing showed too.
